### ISSUE TITLE
Chance 

### ISSUE THREAD

**Issue by rubenio1** [minecrafter/SuperbVote#54]
I have a server where there must to be a chance to get a crate. If done that in the config but I'm Always getting a votecrate. (change is 20).
Also the default reward doesn't work.

Config:
https://pastebin.com/mRPyfCjm

**Comment by astei** [comment]
I'd probably want to replace that chance with `chance-percentage` (if you wanted 20%) or `chance-fractional` (if you wanted a 1/20 chance, that is, 5%).

I don't see anything wrong in the configuration otherwise, and the matchers are working fine. Perhaps it has to do with your `essentials.pay` permission?

**Comment by rubenio1** [comment]
Otherwise it gives a bigg error that that statement is also for default. Then nothing will work. And every player have the perm Essentials.pay.

**Comment by rubenio1** [comment]
The default also doesn't work (that one that gives an apple)

**Comment by astei** [comment]
In other words, it's using the first reward and doesn't match on the second one, because:
* The `chance` matcher was removed in 0.5. (Unfortunately, the removal was incomplete. This is my fault and will be corrected in a future release.)
* Every player has the `essentials.pay` permission.
* `allow-cascading` isn't defined, so it's not collecting additional rewards.
* Therefore, your first reward is being used.

The fix remains the same: Replace the `chance` matcher with `chance-fractional` or `chance-percentage` and it's going to work fine. Next time, [please read the wiki](https://github.com/minecrafter/SuperbVote/wiki/Configuration#if) which explains all the matchers in great detail.

**Comment by rubenio1** [comment]
how can I define allow-cascadering and I want that everyone get the default reward and have a change on the extra how do I must to do that then?

**Comment by astei** [comment]
Everything is explained [on the wiki](https://github.com/minecrafter/SuperbVote/wiki/Configuration#rewards). Please give it a very careful read, it has all the information you need.
